#%%

#make a global estimate for POC flux
import pandas as pd
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import seaborn as sns
import matplotlib.pyplot as plt#
import os
import matplotlib.colors as mcolors
from cmcrameri import cm
from scipy.stats import ks_2samp
from scipy.stats import pearsonr
import xarray as xr
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import datetime as dt
import datetime as dt
from pyproj import Geod
from cmcrameri import cm
from scipy.stats import gaussian_kde
import glob
fp = "/iridisfs/scratch/pe1n24/EST_POC_BAYES/"
fp = "C:/Users/pe1n24/OneDrive - University of Southampton/EST_POC_BAYES/"

#%%
#make list of available files 
files = []
os.chdir(fp)
for f in glob.glob(f"*_summary_stats.csv"):
    files.append(f[:-18])
print(files)

#%%
#import sst and depth (Chla will be later)
#import sst and depth and trasnform
#NOTE I NEED TO CHECK WHERE THE SST COMES FROM/IS MADE
depth = xr.open_dataset(f"")["mask100"]
depth = depth.sortby("lat")
depth = np.log(depth)
sst_ntd = xr.open_dataset(f"")["SST"]
sst_ntd = np.log(sst_ntd + 1.79)

#get lat and lon for plotting/mapping purposes
lats = sst_ntd["lat"]
lons = sst_ntd["lon"]
#%%
#Calculate the area of each 1o cell
#select geoid
g = Geod(ellps = "WGS84") #this is the standard/most accurate eath model

#CODE BETWEEN ***** WAS HELPED GENERATED BY CHATGPT
#*****
#set up an empty cell area array
cell_area = np.zeros(((len(lats)), len(lons)))
for i in range(len(lats)):
    lat = lats[i]
    #print(lat)
    for j in range(len(lons)):
        lon = lons[j]
        latcell = [lat-0.5, lat-0.5, lat+0.5, lat+0.5, lat-0.5]
        loncell = [lon-0.5, lon+0.5, lon+0.5, lon-0.5, lon-0.5]  
        area, _  = g.polygon_area_perimeter(loncell,latcell)
        cell_area[i,j] = area
#*****
#%%

#for each file, generate a global POC estimate 
#(this is not monthly weighted and just for having a look)
for f in files:
    #split so you know how to potentially transform the data
    mets, chl, _ = f.split("_")
    
    #import chla
    chla_ntd = xr.open_dataset(f"")["chlor_a"]
    #transform chla depending on dataset
    if chl == "ugchla":
        chla_ntd = np.log(chla_ntd * 1000)
    else:
        chla_ntd = np.log(chla_ntd)

    #set up lats and lons for mapping purposes
    lats = sst_ntd["lat"]
    lons = sst_ntd["lon"]

    #open beta and gamma datasets 
    betas = pd.read_csv(f"{fp}{f}_beta_vals.csv")
    gammas = pd.read_csv(f"{fp}{f}_gamma_vals.csv")
    
    #set up vars for each gamma (to make code lines shorter)
    gamma1 = np.mean(gammas["gamma.1"])
    gamma2 = np.mean(gammas["gamma.2"])
    gamma3 = np.mean(gammas["gamma.3"])
    gamma4 = np.mean(gammas["gamma.4"])
    gamma5 = np.mean(gammas["gamma.5"])
    gamma6 = np.mean(gammas["gamma.6"])
    gamma7 = np.mean(gammas["gamma.7"])

    beta1 = np.mean(betas["beta.1"])
    beta2 = np.mean(betas["beta.2"])
    beta3 = np.mean(betas["beta.3"])
    beta4 = np.mean(betas["beta.4"])
    beta5 = np.mean(betas["beta.5"])
    beta6 = np.mean(betas["beta.6"])
    beta7 = np.mean(betas["beta.7"])

    #make distribution for mu, sigma and mean poc
    mumap = beta1*np.ones((180,360)) + sst_ntd*beta2 + chla_ntd*beta3 + depth*beta4 + sst_ntd*chla_ntd*beta5 + sst_ntd*depth*beta6 + chla_ntd*depth*beta7
    sigmap =  gamma1*np.ones((180,360)) + sst_ntd*gamma2 + chla_ntd*gamma3 + depth*gamma4 + sst_ntd*chla_ntd*gamma5 + sst_ntd*depth*gamma6 + chla_ntd*depth*gamma7
    pocmap = mumap + (sigmap**2)/2

    #to make globally integrated mean poc estimate 
    #take out of log-space
    pocs = np.exp(pocmap)
    #times by cell area in m2 (mgC/m^2)
    areapocs = pocs * cell_area
    #times for each day to make yearly (mgC/m2/day)
    aypocs = areapocs*365
    #sum for the globe
    pocsum = np.sum(aypocs)
    #to gC
    pocsum = pocsum/1000
    #to PgC
    pocsum = pocsum/(10**15)
    print(pocsum)
#%%
#make global estimates with monthly weighting

#set up how much each month is a fraction of the year
